# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Compile Minecraft Spigot (via BuildTools)
      # You may pin to the exact commit or the version.
      # uses: SpraxDev/Action-SpigotMC@ade5c196b9d9371a057ae520aaeda65075172a28
      uses: SpraxDev/Action-SpigotMC@v4.2.0
      with:
        # Versions to build (separate multiple with ',')
        versions: 1.8.8 # optional, default is latest
        # Should sources be generated?
        generateSrc: false # optional, default is false
        # Should use the SpecialSource Plugin of md_5 to deobfuscate Mojang-NMS-Packets
        remapped: false # optional, default is false
        # Should the documentation be generated?
        generateDoc: false # optional, default is false
        # Should we disable the BuildTools's Java-Version-Check
        disableJavaCheck: false # optional, default is false
        # Disables the check for existing files in the local maven repository
        forceRun: false # optional, default is false
        # The amount of builds allowed to run at a time, set to '-1' to use system's cpu count
        threads: 1 # optional, default is -1
        # Whose BuildTool should be used? (SpigotMC [default])
        buildToolProvider: SpigotMC # optional, default is SpigotMC
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
